package source;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.Map.Entry;
import javax.swing.JOptionPane;



public class StringFormat {

	public static String takeInputFromUser() {
		String inputCaseNumber = JOptionPane.showInputDialog("type case number or participant name");
		return inputCaseNumber;
	}
	
	public static String storeOtherCountryJurisdiction(){
		String Country = "";
		Map<String, String> otherCountryJurisdiction = new HashMap<String, String>();
		String[] inpCountry = {"UNITED STATES","MEXICO","AFGHANISTAN","ALAND ISLANDS","ALBANIA","ALGERIA","AMERICAN SAMOA","ANDORRA","ANGOLA","ANGUILLA","ANTARCTICA","ANTIGUA AND BARBUDA","ARGENTINA","ARMENIA","ARUBA","ASHMORE AND CARTIER ISLANDS","AUSTRALIA","AUSTRIA","AZERBAIJAN","BAHAMAS","BAHRAIN","BAKER ISLAND","BANGLADESH","BARBADOS","BASSAS DA INDIA","BELARUS","BELGIUM","BELIZE","BENIN","BERMUDA","BHUTAN","BOLIVIA","BONAIRE, SAINT EUSTATIUS AND SABA","BOSNIA AND HERZEGOWINA","BOTSWANA","BOUVET ISLAND","BRAZIL","BRITISH INDIAN OCEAN TERRITORY","BRUNEI DARUSSALAM","BULGARIA","BURKINA FASO","BURUNDI","CAMBODIA","CAMEROON","CANADA","CAPE VERDE","CAYMAN ISLANDS","CENTRAL AFRICAN REPUBLIC","CHAD","CHILE","CHINA","CHRISTMAS ISLAND","CLIPPERTON ISLAND","COCOS (KEELING) ISLANDS","COLOMBIA","COMOROS","CONGO","CONGO, THE DEMOCRATIC REPUBLIC OF THE","COOK ISLANDS","CORAL SEA ISLANDS","COSTA RICA","COTE D'IVOIRE","CROATIA (local name: Hrvatska)","CUBA","CURACAO","CYPRUS","CZECH REPUBLIC","DENMARK","DJIBOUTI","DOMINICA","DOMINICAN REPUBLIC","EAST TIMOR","ECUADOR","EGYPT","EL SALVADOR","EQUATORIAL GUINEA","ERITREA","ESTONIA","ETHIOPIA","EUROPA ISLAND","FALKLAND ISLANDS (MALVINAS)","FAROE ISLANDS","FIJI","FINLAND","FRANCE","FRENCH GUIANA","FRENCH POLYNESIA","FRENCH SOUTHERN TERRITORIES","GABON","GAMBIA","GAZA STRIP","GEORGIA","GERMANY","GHANA","GIBRALTAR","GLORIOSO ISLANDS","GREECE","GREENLAND","GRENADA","GUADELOUPE","GUATEMALA","GUERNSEY","GUINEA","GUINEA-BISSAU","GUYANA","HAITI","HEARD AND MC DONALD ISLANDS","HONDURAS","HONG KONG","HOWLAND ISLAND","HUNGARY","ICELAND","INDIA","INDONESIA","IRAN (ISLAMIC REPUBLIC OF)","IRAQ","IRELAND","ISLE OF MAN","ISRAEL","ITALY","JAMAICA","JAPAN","JARVIS ISLAND","JERSEY","JOHNSTON ATOLL","JORDAN","JUAN DE NOVA ISLAND","KAZAKHSTAN","KENYA","KINGMAN REEF","KIRIBATI","KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF","KOREA, REPUBLIC OF","KUWAIT","KYRGYZSTAN","LAO PEOPLE'S DEMOCRATIC REPUBLIC","LATVIA","LEBANON","LESOTHO","LIBERIA","LIBYAN ARAB JAMAHIRIYA","LIECHTENSTEIN","LITHUANIA","LUXEMBOURG","MACAU","MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF","MADAGASCAR","MALAWI","MALAYSIA","MALDIVES","MALI","MALTA","MARSHALL ISLANDS","MARTINIQUE","MAURITANIA","MAURITIUS","MAYOTTE","MICRONESIA, FEDERATED STATES OF","MIDWAY ISLANDS","MOLDOVA, REPUBLIC OF","MONACO","MONGOLIA","MONTENEGRO","MONTSERRAT","MOROCCO","MOZAMBIQUE","MYANMAR","NAMIBIA","NAURU","NAVASSA ISLAND","NEPAL","NETHERLANDS","NETHERLANDS ANTILLES","NEW CALEDONIA","NEW ZEALAND","NICARAGUA","NIGER","NIGERIA","NIUE","NORFOLK ISLAND","NORTHERN MARIANA ISLANDS","NORWAY","OMAN","PAKISTAN","PALAU","PALESTINIAN TERRITORY, OCCUPIED","PALMYRA ATOLL","PANAMA","PAPUA NEW GUINEA","PARACEL ISLANDS","PARAGUAY","PERU","PHILIPPINES","PITCAIRN","POLAND","PORTUGAL","PUERTO RICO","QATAR","REUNION","ROMANIA","RUSSIAN FEDERATION","RWANDA","SAINT BARTHELEMY","SAINT KITTS AND NEVIS","SAINT LUCIA","SAINT MARTIN (FRENCH PART)","SAINT VINCENT AND THE GRENADINES","SAMOA","SAN MARINO","SAO TOME AND PRINCIPE","SAUDI ARABIA","SENEGAL","SERBIA","SERBIA AND MONTENEGRO","SEYCHELLES","SIERRA LEONE","SINGAPORE","SINT MAARTEN (DUTCH PART)","SLOVAKIA (SLOVAK REPUBLIC)","SLOVENIA","SOLOMON ISLANDS","SOMALIA","SOUTH AFRICA","SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS","SPAIN","SPRATLY ISLANDS","SRI LANKA","ST. HELENA","ST. PIERRE AND MIQUELON","SUDAN","SURINAME","SVALBARD AND JAN MAYEN ISLANDS","SWAZILAND","SWEDEN","SWITZERLAND","SYRIAN ARAB REPUBLIC","TAIWAN","TAJIKISTAN","TANZANIA, UNITED REPUBLIC OF","THAILAND","TOGO","TOKELAU","TONGA","TRINIDAD AND TOBAGO","TROMELIN ISLAND","TUNISIA","TURKEY","TURKMENISTAN","TURKS AND CAICOS ISLANDS","TUVALU","UGANDA","UKRAINE","UNITED ARAB EMIRATES","UNITED KINGDOM","UNITED STATES MINOR OUTLYING ISLANDS","UNKNOWN","URUGUAY","UZBEKISTAN","VANUATU","VATICAN CITY STATE (HOLY SEE)","VENEZUELA","VIETNAM","VIRGIN ISLANDS (BRITISH)","VIRGIN ISLANDS (U.S.)","WALLIS AND FUTUNA ISLANDS","WESTERN SAHARA","YEMEN","ZAMBIA","ZIMBABWE"};
		String[] inpCountryCode = {"US","MX","AF","AX","AL","DZ","AS","AD","AO","AI","AQ","AG","AR","AM","AW","AC","AU","AT","AZ","BS","BH","FQ","BD","BB","BX","BY","BE","BZ","BJ","BM","BT","BO","BQ","BA","BW","BV","BR","IO","BN","BG","BF","BI","KH","CM","CA","CV","KY","CF","TD","CL","CN","CX","IP","CC","CO","KM","CG","CD","CK","CB","CR","CI","HR","CU","CW","CY","CZ","DK","DJ","DM","DO","TL","EC","EG","SV","GQ","ER","EE","ET","EU","FK","FO","FJ","FI","FR","GF","PF","TF","GA","GM","GZ","GE","DE","GH","GI","GO","GR","GL","GD","GP","GT","GG","GN","GW","GY","HT","HM","HN","HK","HQ","HU","IS","IN","ID","IR","IQ","IE","IM","IL","IT","JM","JP","DQ","JE","JQ","JO","JU","KZ","KE","KQ","KI","KP","KR","KW","KG","LA","LV","LB","LS","LR","LY","LI","LT","LU","MO","MK","MG","MW","MY","MV","ML","MT","MH","MQ","MR","MU","YT","FM","MI","MD","MC","MN","ME","MS","MA","MZ","MM","NA","NR","BQ","NP","NL","AN","NC","NZ","NI","NE","NG","NU","NF","MP","NO","OM","PK","PW","PS","LQ","PA","PG","PI","PY","PE","PH","PN","PL","PT","PR","QA","RE","RO","RU","RW","BL","KN","LC","MF","VC","WS","SM","ST","SA","SN","RS","CS","SC","SL","SG","SX","SK","SI","SB","SO","ZA","GS","ES","SP","LK","SH","PM","SD","SR","SJ","SZ","SE","CH","SY","TW","TJ","TZ","TH","TG","TK","TO","TT","TE","TN","TR","TM","TC","TV","UG","UA","AE","GB","UM","ZZ","UY","UZ","VU","VA","VE","VN","VG","VI","WF","EH","YE","ZM","ZW"};
		ArrayList<String> key = new ArrayList<String>();
		ArrayList<String> value = new ArrayList<String>();
		
		for (int i = 0; i < inpCountry.length; i++) {
			key.add(inpCountryCode[i]);
			value.add(inpCountry[i]);
			otherCountryJurisdiction.put(key.get(i), value.get(i));


		}
		
		
		
		String storeCountryCode = takeInputFromUser();
		System.out.println("Typed Country Code: " + storeCountryCode);
		
		for(Entry<String, String> key1 : otherCountryJurisdiction.entrySet()){
			String s = key1.getKey();
			if(s.equals(storeCountryCode.toUpperCase())){
				
				System.out.println("Country received: " + key1.getValue());
				Country = key1.getValue();
			}
		}
		
		System.out.println("-----------------------------------------------");
		
		return Country;
		
	}
	
	

	public static void main(String[] args) {
		storeOtherCountryJurisdiction();
		
	}

}
